[2020-06-08 19:28:32,818] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: my_dag.source3 2020-06-08T13:49:42.367179+00:00 [queued]>
[2020-06-08 19:28:32,829] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: my_dag.source3 2020-06-08T13:49:42.367179+00:00 [queued]>
[2020-06-08 19:28:32,829] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-08 19:28:32,829] {taskinstance.py:880} INFO - Starting attempt 2 of 2
[2020-06-08 19:28:32,829] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-08 19:28:32,847] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): source3> on 2020-06-08T13:49:42.367179+00:00
[2020-06-08 19:28:32,849] {standard_task_runner.py:53} INFO - Started process 12894 to run task
[2020-06-08 19:28:32,899] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: my_dag.source3 2020-06-08T13:49:42.367179+00:00 [running]> nineleaps-ThinkPad-E470
[2020-06-08 19:28:32,973] {taskinstance.py:1145} ERROR - 'ti'
Traceback (most recent call last):
  File "/home/nineleaps/.local/lib/python2.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/nineleaps/.local/lib/python2.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/nineleaps/.local/lib/python2.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nineleaps/airflow/dags/airflow_tasks.py", line 84, in percentage_upload
    ti = kwargs['ti']
KeyError: 'ti'
[2020-06-08 19:28:32,974] {taskinstance.py:1187} INFO - All retries failed; marking task as FAILED.dag_id=my_dag, task_id=source3, execution_date=20200608T134942, start_date=20200608T135832, end_date=20200608T135832
[2020-06-08 19:28:42,812] {logging_mixin.py:112} INFO - [2020-06-08 19:28:42,811] {local_task_job.py:103} INFO - Task exited with return code 1
