[2020-06-08 20:08:05,088] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: my_dag.source3 2020-06-08T14:30:23.447536+00:00 [queued]>
[2020-06-08 20:08:05,098] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: my_dag.source3 2020-06-08T14:30:23.447536+00:00 [queued]>
[2020-06-08 20:08:05,099] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-08 20:08:05,099] {taskinstance.py:880} INFO - Starting attempt 2 of 2
[2020-06-08 20:08:05,099] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-08 20:08:05,130] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): source3> on 2020-06-08T14:30:23.447536+00:00
[2020-06-08 20:08:05,132] {standard_task_runner.py:53} INFO - Started process 16013 to run task
[2020-06-08 20:08:05,207] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: my_dag.source3 2020-06-08T14:30:23.447536+00:00 [running]> nineleaps-ThinkPad-E470
[2020-06-08 20:08:05,281] {logging_mixin.py:112} INFO - (<type 'NoneType'>, None)
[2020-06-08 20:08:05,281] {taskinstance.py:1145} ERROR - unsupported operand type(s) for /: 'NoneType' and 'float'
Traceback (most recent call last):
  File "/home/nineleaps/.local/lib/python2.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/nineleaps/.local/lib/python2.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/nineleaps/.local/lib/python2.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nineleaps/airflow/dags/airflow_tasks.py", line 88, in percentage_upload
    print("percentage = {}".format((v1 / total_rows-1) * 100))
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
[2020-06-08 20:08:05,282] {taskinstance.py:1187} INFO - All retries failed; marking task as FAILED.dag_id=my_dag, task_id=source3, execution_date=20200608T143023, start_date=20200608T143805, end_date=20200608T143805
[2020-06-08 20:08:15,079] {logging_mixin.py:112} INFO - [2020-06-08 20:08:15,078] {local_task_job.py:103} INFO - Task exited with return code 1
