[2020-06-08 19:05:54,301] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: my_dag.source3 2020-06-08T13:33:03.112358+00:00 [queued]>
[2020-06-08 19:05:54,310] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: my_dag.source3 2020-06-08T13:33:03.112358+00:00 [queued]>
[2020-06-08 19:05:54,310] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-08 19:05:54,310] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-08 19:05:54,310] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-08 19:05:54,329] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): source3> on 2020-06-08T13:33:03.112358+00:00
[2020-06-08 19:05:54,334] {standard_task_runner.py:53} INFO - Started process 11481 to run task
[2020-06-08 19:05:54,403] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: my_dag.source3 2020-06-08T13:33:03.112358+00:00 [running]> nineleaps-ThinkPad-E470
[2020-06-08 19:05:54,473] {taskinstance.py:1145} ERROR - float division by zero
Traceback (most recent call last):
  File "/home/nineleaps/.local/lib/python2.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/nineleaps/.local/lib/python2.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/nineleaps/.local/lib/python2.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nineleaps/airflow/dags/airflow_tasks.py", line 81, in percentage_upload
    print (((total_rows-1)/rows_uploaded)*100)
ZeroDivisionError: float division by zero
[2020-06-08 19:05:54,474] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-06-08 19:06:04,288] {logging_mixin.py:112} INFO - [2020-06-08 19:06:04,287] {local_task_job.py:103} INFO - Task exited with return code 1
